######################################################################
# Automatically generated by qmake (3.0) sob. kwi 19 21:05:11 2014
######################################################################

TEMPLATE = app
TARGET = CSGOQT
INCLUDEPATH += -I /usr/include/jsoncpp .
QT += widgets core
LIBS+= -lcurl -l:libjsoncpp.so
# Input
HEADERS += json.h qt.h
SOURCES += json.cpp main.cpp qt.cpp
